spring:
  profiles:
    active: local

---
spring.profiles: local
spring.profiles.include: local-social

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/shoppingmall
    username: root
    password: root
  jpa:
    database: mysql
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


---
spring.profiles: set1
spring.profiles.include: real-db, real-social-set1

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db, real-social-set2

server:
  port: 8082